{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.terminals.kitty;
in
{
  options.terminals.kitty = {
    enable = lib.mkEnableOption "Install Kitty terminal emulator via Nix.";

    config = {
      enable = lib.mkEnableOption "Manage Kitty configuration.";

      dmsIntegration = {
        enable = lib.mkEnableOption "Enable DMS theme/tab integration includes.";
      };

      font = {
        name = lib.mkOption {
          type = lib.types.str;
          default = "JetBrainsMono Nerd Font";
        };

        package = lib.mkOption {
          type = lib.types.package;
          default = pkgs.nerd-fonts.jetbrains-mono;
        };
      };

      settings = lib.mkOption {
        type = lib.types.attrsOf lib.types.anything;
        default = {
          shell_integration = "no-rc";
          enable_audio_bell = "no";
          hide_window_decorations = "yes";
          confirm_os_window_close = 0;
          font_size = 12;
          background_opacity = 1;
        };
      };
    };
  };

  config = lib.mkMerge [

    # ---------------------------
    # Install kitty via nix
    # ---------------------------
    (lib.mkIf cfg.enable {
      programs.kitty.enable = true;
    })

    # ---------------------------
    # Config mode (works without nix kitty)
    # ---------------------------
    (lib.mkIf cfg.config.enable {
      home.file.".config/kitty/kitty.conf".text =
        let
          settingsStr = lib.concatStringsSep "\n" (
            lib.mapAttrsToList (k: v: "${k} ${toString v}") cfg.config.settings
          );

          dmsIncludes = lib.optionalString cfg.config.dmsIntegration.enable ''
            include ~/.config/kitty/dank-theme.conf
            include ~/.config/kitty/dank-tabs.conf
          '';
        in
        ''
          # generated by nix

          ${settingsStr}

          font_family ${cfg.config.font.name}

          ${dmsIncludes}
        '';

      home.packages = [ cfg.config.font.package ];
    })

    # ---------------------------
    # Nix-managed kitty mode
    # ---------------------------
    (lib.mkIf (cfg.enable && cfg.config.dmsIntegration.enable) {
      programs.kitty.extraConfig = ''
        include ~/.config/kitty/dank-theme.conf
        include ~/.config/kitty/dank-tabs.conf
      '';
    })
  ];
}
